---
# tasks file for application
- name: Copy docker compose file
  copy:
    src: ../files/
    dest: tmp/
- name: Deploy Docker Compose stack
  community.docker.docker_compose:
    project_src: /tmp
    files:
    - docker-compose.yaml